site_name: THRUST Technical Docs
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: black
  icon:
    logo: material/rocket-launch
markdown_extensions:
#  - pymdownx.arithmatex:
#      generic: true
plugins:
  - git-authors:
      show_contribution: true
      show_line_count: true
      count_empty_lines: true
      fallback_to_empty: false
      exclude:
          - index.md
      enabled: true
#extra_javascript:
#  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - 'assets/css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

extra_javascript:
  - 'assets/js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js'
