site_name: THRUST Project Knowledge

theme:
  name: material
  features:
    - navigation.tabs
  icon:
    logo: material/rocket-launch
  font:
    text: 'IBM Plex Sans'
    code: 'Fira Code'
  custom_dir: docs/overrides
  palette:
  - scheme: default
    primary: black
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: slate
    primary: black
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:
  - search
  - git-authors:
      show_contribution: false
      show_line_count: false
      count_empty_lines: false
      fallback_to_empty: false
      enabled: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details

extra_css:
  - 'https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css'

extra_javascript:
  - 'assets/js/math.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/contrib/auto-render.min.js'

repo_url: https://github.com/thrust-team/docs
repo_name: thrust-team/docs
